// Generated by GitHub Copilot
'use client';

/**
 * EXIF情報表示コンポーネント
 * 画像のメタデータ（EXIF）情報を表形式で表示
 */
export function ExifViewer({ exifData }) {
  return (
    <section className="p-6 rounded-lg bg-white dark:bg-gray-800 shadow-md mb-8">
      <h2 className="text-xl font-semibold mb-4">EXIF情報</h2>
      <div className="max-h-96 overflow-y-auto p-4 rounded-md bg-gray-100 dark:bg-gray-700">
        {exifData && Object.keys(exifData).length > 0 ? (
          <table className="w-full text-sm">
            <thead>
              <tr className="border-b border-gray-500">
                <th className="text-left p-2 text-gray-700 dark:text-gray-300">プロパティ</th>
                <th className="text-left p-2 text-gray-700 dark:text-gray-300">値</th>
              </tr>
            </thead>
            <tbody>
              {Object.entries(exifData).map(([key, value], index) => (
                <tr key={key} className={index % 2 === 0 ? 'bg-white dark:bg-gray-800' : ''}>
                  <td className="p-2 text-gray-700 dark:text-gray-300 font-medium">{key}</td>
                  <td className="p-2 text-gray-700 dark:text-gray-300">
                    {Array.isArray(value) ? value.join(', ') : String(value)}
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        ) : (
          <div className="flex flex-col items-center justify-center py-8 text-center">
            <svg xmlns="http://www.w3.org/2000/svg" className="h-12 w-12 mb-4 text-gray-400 dark:text-gray-500" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M13 16h-1v-4h-1m1-4h.01M6 20h12a2 2 0 002-2V6a2 2 0 00-2-2H6a2 2 0 00-2 2v12a2 2 0 002 2z" />
            </svg>
            <p className="text-lg text-gray-600 dark:text-gray-300">この画像からEXIF情報を取得できませんでした。</p>
            <p className="mt-2 text-gray-500 dark:text-gray-400">
              EXIF情報が含まれていないか、またはブラウザでサポートされていない形式の可能性があります。
            </p>
          </div>
        )}
      </div>
    </section>
  );
}