// Generated by GitHub Copilot
'use client';

import { toast } from 'react-hot-toast';
import { saveFile } from '@/utils/fileUtils';

/**
 * 画像の出力操作を提供するカスタムフック
 * @returns {Object} 画像の保存やコピーに関する関数
 */
export function useImageOutput() {
  /**
   * 処理した画像を保存する
   * @param {Object} processedImage 処理後の画像情報
   * @param {string} format ファイル形式
   */
  const saveImage = (processedImage, format = 'png') => {
    if (!processedImage) return;
    
    const formatExtension = format || 'png';
    const fileName = `image-${Date.now()}.${formatExtension}`;
    
    saveFile(processedImage.blob, fileName);
  };

  /**
   * 処理した画像をクリップボードにコピーする
   * @param {Object} processedImage 処理後の画像情報
   * @returns {Promise<boolean>} コピー成功時はtrue、失敗時はfalse
   */
  const copyImageToClipboard = async (processedImage) => {
    if (!processedImage) return false;
    
    try {
      // Clipboard APIを使用してBlobを直接クリップボードにコピー
      await navigator.clipboard.write([
        new ClipboardItem({
          [processedImage.type]: processedImage.blob
        })
      ]);
      
      toast.success('画像をクリップボードにコピーしました。');
      return true;
    } catch (error) {
      console.error('クリップボードへのコピーに失敗しました', error);
      toast.error('画像のコピーに失敗しました。ブラウザがこの機能をサポートしていないか、権限がありません。');
      return false;
    }
  };

  return {
    saveImage,
    copyImageToClipboard
  };
}