import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { Toaster } from 'react-hot-toast';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Toolbox - 便利ツール集",
  description: "様々な便利なツールを提供するWebアプリ",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ja" className="h-screen">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col h-screen overflow-hidden`}
      >
        {/* トースト通知コンポーネントを追加 */}
        <Toaster
          position="top-right"
          toastOptions={{
            // デフォルトのスタイル設定
            success: {
              duration: 3000,
              style: {
                background: '#10B981',
                color: '#fff',
              },
            },
            error: {
              duration: 4000,
              style: {
                background: '#EF4444',
                color: '#fff',
              },
            },
          }}
        />
        <header className="bg-gray-800 text-white shadow-md">
          <nav className="max-w-6xl mx-auto px-4 py-3 flex items-center justify-between">
            <Link href="/" className="text-xl font-bold">Toolbox</Link>
            <ul className="flex space-x-6">
              <li>
                <Link href="/" className="hover:text-gray-300 transition-colors">
                  ホーム
                </Link>
              </li>
              <li>
                <Link href="/images" className="hover:text-gray-300 transition-colors">
                  画像処理
                </Link>
              </li>
              <li>
                <Link href="/ai/chat" className="hover:text-gray-300 transition-colors">
                  AIチャット
                </Link>
              </li>
            </ul>
          </nav>
        </header>
        <main className="flex-grow bg-gray-50 dark:bg-gray-900 text-gray-900 dark:text-gray-100 transition-colors duration-200 overflow-auto">
          {children}
        </main>
        <footer className="bg-gray-800 text-white py-4">
          <div className="max-w-6xl mx-auto px-4 text-center text-sm">
            <p>Generated by GitHub Copilot.</p>
          </div>
        </footer>
      </body>
    </html>
  );
}
