// Generated by GitHub Copilot
'use client';

/**
 * ファイルとして保存する
 * @param {Blob} blob 保存するBlobオブジェクト
 * @param {string} fileName ファイル名（拡張子を含む）
 */
export const saveFile = (blob, fileName) => {
  if (!blob || !fileName) return;
  
  // Object URLを作成
  const url = URL.createObjectURL(blob);
  
  // 一時的なa要素を作成してダウンロードを実行
  const link = document.createElement('a');
  link.href = url;
  link.download = fileName;
  link.style.display = 'none';
  
  // DOMに追加、クリックをシミュレーション、そして削除
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  
  // Object URLを解放してメモリリークを防止
  setTimeout(() => URL.revokeObjectURL(url), 100);
}

/**
 * 画像のサイズをKB単位で計算する
 * @param {File|Blob} blob - 画像ファイルまたはBlob
 * @returns {string} KB単位のサイズ（小数点以下2桁まで）
 */
export const calculateFileSize = (blob) => {
  const size = blob.size;
  // KB単位に変換（小数点以下2桁まで）
  return (size / 1024).toFixed(2);
};
