// Generated by GitHub Copilot

import { callChatCompletion, DEFAULT_MODEL } from '@/services/openai';

/**
 * チャットAPIのPOSTリクエストを処理する
 * @param {Request} request リクエストオブジェクト
 * @returns {Response} レスポンスオブジェクト
 */
export async function POST(request) {
  try {
    // リクエストボディからメッセージ、モデル、APIキーを取得
    const { messages, model = DEFAULT_MODEL, apiKey } = await request.json();
    
    if (!messages || !Array.isArray(messages) || messages.length === 0) {
      return Response.json({ error: 'メッセージが正しい形式ではありません' }, { status: 400 });
    }
    
    if (!apiKey) {
      return Response.json({ error: 'APIキーが指定されていません' }, { status: 400 });
    }

    // OpenAI APIを呼び出す（クライアントから送られたAPIキーを使用）
    const response = await callChatCompletion(messages, { model, apiKey });
    
    // レスポンスを返却
    return Response.json({
      message: response.choices[0].message
    });
  } catch (error) {
    console.error('AIチャットAPIエラー:', error);
    return Response.json({ error: error.message || 'AIチャットの処理中にエラーが発生しました' }, { status: 500 });
  }
}